[package]
name = "retos-kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader_api = "0.11.10"
spin = "0.9.8"
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
noto-sans-mono-bitmap = { version = "0.3.1", features = ["regular", "size_16", "unicode-basic-latin", "unicode-specials"]}